version: "3.9"
services:
  db:
    image: postgres:15.13-alpine
    container_name: fraud_db
    environment:
      POSTGRES_DB: frauddb
      POSTGRES_USER: fraud
      POSTGRES_PASSWORD: fraudpass
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fraud -d frauddb"]
      interval: 5s
      timeout: 3s
      retries: 10

  app:
    build: .
    container_name: fraud_app
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/frauddb
      SPRING_DATASOURCE_USERNAME: fraud
      SPRING_DATASOURCE_PASSWORD: fraudpass
      SPRING_PROFILES_ACTIVE: docker
      JAVA_TOOL_OPTIONS: "-Dflyway.postgresql.compatibility=15"
    ports:
      - "8080:8080"

volumes:
  db_data:

