spring:
  application:
    name: fraud-rule-engine

  datasource:
    url: jdbc:postgresql://fraud_db:5432/frauddb
    username: fraud
    password: fraudpass

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate.jdbc.time_zone: UTC

  flyway:
    enabled: true
    baseline-on-migrate: false
    validate-on-migrate: true
    mixed: true
    baseline-version: 1
    postgresql:
      compatibility: "15"

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

info:
  app:
    name: fraud-rule-engine
    description: Fraud detection microservice with configurable rule engine
    version: 1.0.0